### ISSUE TITLE
Create medicine

### ISSUE THREAD

**Issue by Andres-Aliendre** [Andres-Aliendre/MedicationScheduler#1]
**Epic:** None

**Priority:** High

**Story Points:** 3

**Description:** \
As a user, I want to create new medicine in my medicines, so I can add them to a treatment or just have them registered.

**Acceptance Criteria:**
- _Given_ the medicines menu and the "add medicine" button,
_When_ the user clicks on it,
_Then_ a form to fill in the data of the medicine will be shown. (name, type)
- _Given_ the new medicine form,
_When_ the user fills all fields _and_ clicks on the "create" button,
_Then_ the new medicine should appear on the medicines section

**Tasks:**
- [ ] create base classes for medicines
- [ ] crate medicines menu
- [ ] create new medicine form
- [ ] create medicine card
- [ ] create medicine details view
